# fly.toml app configuration file generated for iscchatbot on 2023-05-22T17:20:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "iscchatbot"
primary_region = "bog"
